### ISSUE TITLE
ImageJ plugin import remote with https

### ISSUE THREAD

**Issue by dpwrussell** [openmicroscopy/bioformats#1851]
When trying to import a a remote url which is https, it will fail. Presumably this is because it does not recognise the protocol and defaults to trying to open it as a file:

```
java.io.FileNotFoundException: https:/s3.amazonaws.com/dpwr/s3test/bus.png (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:123)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:139)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:148)
	at loci.common.Location.getHandle(Location.java:321)
	at loci.common.Location.getHandle(Location.java:291)
	at loci.common.Location.getHandle(Location.java:281)
	at loci.common.Location.getHandle(Location.java:271)
	at loci.common.Location.checkValidId(Location.java:346)
	at loci.formats.ImageReader.getReader(ImageReader.java:173)
	at loci.plugins.in.ImportProcess.createBaseReader(ImportProcess.java:628)
	at loci.plugins.in.ImportProcess.initializeReader(ImportProcess.java:486)
	at loci.plugins.in.ImportProcess.execute(ImportProcess.java:139)
	at loci.plugins.in.Importer.showDialogs(Importer.java:137)
	at loci.plugins.in.Importer.run(Importer.java:75)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
	at ij.IJ.runUserPlugIn(IJ.java:199)
	at ij.IJ.runPlugIn(IJ.java:163)
	at ij.Executer.runCommand(Executer.java:132)
	at ij.Executer.run(Executer.java:65)
	at java.lang.Thread.run(Thread.java:745)
```

ImageJ's `File -> Import -> URL` does manage to open from https URLs.

**Comment by bramalingam** [comment]
Hi Douglas, 

Thank you for reporting the bug. The https case was not handled in the importer, and the following PR should fix the same,
https://github.com/openmicroscopy/bioformats/pull/1854

Best,
Balaji
