### ISSUE TITLE
Problems opening new SlideBook files

### ISSUE THREAD

**Issue by ctrueden** [openmicroscopy/bioformats#2008]
Originally reported as [Fiji bug #1161](http://fiji.sc/bugzilla/show_bug.cgi?id=1161).

When opening newer SlideBook files with an up-to-date Fiji as of this writing, the following exception is thrown:
```
(Fiji Is Just) ImageJ 2.0.0-rc-39/1.50b; Java 1.8.0_45 [64-bit]; Mac OS X 10.10.5; 36MB of 4175MB (<1%)
 
java.lang.ArrayIndexOutOfBoundsException: 0
	at loci.formats.in.SlidebookReader.initFile(SlidebookReader.java:634)
	at loci.formats.FormatReader.setId(FormatReader.java:1426)
	at loci.plugins.in.ImportProcess.initializeFile(ImportProcess.java:505)
	at loci.plugins.in.ImportProcess.execute(ImportProcess.java:143)
	at loci.plugins.in.Importer.showDialogs(Importer.java:137)
	at loci.plugins.in.Importer.run(Importer.java:75)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
	at ij.IJ.runUserPlugIn(IJ.java:212)
	at ij.IJ.runPlugIn(IJ.java:176)
	at ij.IJ.runPlugIn(IJ.java:165)
	at HandleExtraFileTypes.openImage(HandleExtraFileTypes.java:499)
	at HandleExtraFileTypes.run(HandleExtraFileTypes.java:72)
	at ij.IJ.runUserPlugIn(IJ.java:212)
	at ij.IJ.runPlugIn(IJ.java:176)
	at ij.IJ.runPlugIn(IJ.java:165)
	at ij.io.Opener.openWithHandleExtraFileTypes(Opener.java:503)
	at ij.io.Opener.openImage(Opener.java:369)
	at ij.io.Opener.openImage(Opener.java:243)
	at ij.io.Opener.open(Opener.java:110)
	at ij.io.Opener.openAndAddToRecent(Opener.java:292)
	at ij.plugin.DragAndDrop.openFile(DragAndDrop.java:181)
	at ij.plugin.DragAndDrop.run(DragAndDrop.java:152)
	at java.lang.Thread.run(Thread.java:745)
```

On my Windows 7 VM, the error is different, due to the use of the `SlideBook6Reader` native linkage:
```
(Fiji Is Just) ImageJ 2.0.0-rc-39/1.50b; Java 1.8.0_05 [64-bit]; Windows 7 6.1; 32MB of 1527MB (2%)
 
java.lang.AssertionError: Failed with exception: The file is not a valid SlideBook document. Z plane index too large.

	at loci.formats.in.SlideBook6Reader.getZPosition(Native Method)
	at loci.formats.in.SlideBook6Reader.initFile(SlideBook6Reader.java:277)
	at loci.formats.FormatReader.setId(FormatReader.java:1426)
	at loci.plugins.in.ImportProcess.initializeFile(ImportProcess.java:505)
	at loci.plugins.in.ImportProcess.execute(ImportProcess.java:143)
	at loci.plugins.in.Importer.showDialogs(Importer.java:137)
	at loci.plugins.in.Importer.run(Importer.java:75)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
	at ij.IJ.runUserPlugIn(IJ.java:212)
	at ij.IJ.runPlugIn(IJ.java:176)
	at ij.Executer.runCommand(Executer.java:132)
	at ij.Executer.run(Executer.java:65)
	at java.lang.Thread.run(Thread.java:745)
```

The original reporter, Glen MacDonald, states that the file works on his Windows 7 systems—probably because those machines have a different/newer version of the SlideBook native library?

Sample file:
* http://fiji.sc/bugzilla/attachment.cgi?id=262

**Comment by melissalinkert** [comment]
Added to https://trac.openmicroscopy.org/ome/ticket/12919 (currently scheduled for 5.1.6).
