### ISSUE TITLE
Loading large jpeg files fails

### ISSUE THREAD

**Issue by felixveysseyre** [openmicroscopy/bioformats#2132]
Hello,

(This issue is a copy of a topic opened on OME forum : https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=7957)

I am currently trying to convert a very large JPEG image (65500px x 53090px) with bfconvert.

When I run the executable with this image, I got the following stack trace :
```
../bftools/bfconvert -bigtiff -series 0 "/.../.../x-3.jpeg" "/.../.../TIFF/%z.%t.tiff" 2>&1
/.../.../x-3.jpeg
JPEGReader initializing /.../.../x-3.jpeg
Populating metadata
Exception in thread "main" java.lang.IllegalArgumentException: width*height > Integer.MAX_VALUE!
   at javax.imageio.ImageReader.getDestination(ImageReader.java:2823)
   at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1046)
   at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1014)
   at javax.imageio.ImageIO.read(ImageIO.java:1422)
   at javax.imageio.ImageIO.read(ImageIO.java:1326)
   at loci.formats.in.ImageIOReader.initImage(ImageIOReader.java:150)
   at loci.formats.in.ImageIOReader.initFile(ImageIOReader.java:122)
   at loci.formats.in.JPEGReader$DefaultJPEGReader.initFile(JPEGReader.java:190)
   at loci.formats.FormatReader.setId(FormatReader.java:1426)
   at loci.formats.DelegateReader.setId(DelegateReader.java:290)
   at loci.formats.in.JPEGReader.setId(JPEGReader.java:89)
   at loci.formats.ImageReader.setId(ImageReader.java:835)
   at loci.formats.tools.ImageConverter.testConvert(ImageConverter.java:367)
   at loci.formats.tools.ImageConverter.main(ImageConverter.java:874)
```

I am currently using this version of bfconvert:
```
Version: 5.1.4
VCS revision: 05840624ab3d1d1dca14d1ccfebabcb61c42ec27
Build date: 4 September 2015
```

Do you advise any other solution to convert this image to a TIFF file ?

Regards,
Félix

**Comment by melissalinkert** [comment]
As posted to the forum thread, https://trello.com/c/M8PidMnv/58-use-jpegturboservice-to-read-large-jpeg-images records the plan to fix this before the 5.2.0 release, so closing in favor of the original forum thread and Trello card.
