### ISSUE TITLE
Error reading .bip files (Kodak)

### ISSUE THREAD

**Issue by andrewjanke** [openmicroscopy/bioformats#2491]
We have some Kodak Molecular Imaging files and it seems that the CCD temperature is not what the reader is expecting:

```
cai-zeep:NIF062-fix-tiffs$ showinf -no-upgrade -novalid -debug one/fnarg/bob.bip
Using mapped byte buffer? false
Checking file format [Kodak Molecular Imaging]
Initializing reader
Location.mapFile: embedded-stream.raw -> null
KodakReader initializing one/fnarg/bob.bip
KodakReader initializing one/fnarg/bob.bip
loci.formats.in.KodakReader.initFile(one/fnarg/bob.bip)
Loaded properties from: services.properties
Added interface interface loci.formats.services.POIService and implementation class loci.formats.services.POIServiceImpl
Added interface interface loci.formats.services.MDBService and implementation class loci.formats.services.MDBServiceImpl
Added interface interface loci.formats.services.JPEGTurboService and implementation class loci.formats.services.JPEGTurboServiceImpl
Added interface interface loci.formats.services.JAIIIOService and implementation class loci.formats.services.JAIIIOServiceImpl
Added interface interface loci.formats.services.WlzService and implementation class loci.formats.services.WlzServiceImpl
Added interface interface loci.formats.services.NetCDFService and implementation class loci.formats.services.NetCDFServiceImpl
Added interface interface loci.formats.services.MetakitService and implementation class loci.formats.services.MetakitServiceImpl
Added interface interface loci.formats.services.LuraWaveService and implementation class loci.formats.services.LuraWaveServiceImpl
Added interface interface loci.formats.services.OMEXMLService and implementation class loci.formats.services.OMEXMLServiceImpl
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1911)
	at loci.formats.in.KodakReader.readExtraMetadata(KodakReader.java:228)
	at loci.formats.in.KodakReader.initFile(KodakReader.java:131)
	at loci.formats.FormatReader.setId(FormatReader.java:1319)
	at loci.formats.ImageReader.setId(ImageReader.java:757)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:573)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:993)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1075)
```

If I go digging in the file I find this:

    ` CCD Temperature:>--0xED    `

At which point if I do something like this:

  ` $ sed '/CCD\ Temperature/d' one/fnarg/bob.bip > out.bip`

```
cai-zeep:NIF062-fix-tiffs$ showinf out.bip 
Checking file format [Kodak Molecular Imaging]
Initializing reader
KodakReader initializing out.bip
Initialization took 0.286s

Java does not support display of unnormalized floating point data.
Please use the '-normalize' option to avoid receiving a cryptic exception.

Reading core metadata
Filename = out.bip
Series count = 1
Series #0 :
	Image count = 1
	RGB = false (1) 
	Interleaved = false
	Indexed = false (false color)
	Width = 512
	Height = 512
	SizeZ = 1
	SizeT = 1
	SizeC = 1
	Thumbnail size = 128 x 128
	Endianness = motorola (big)
	Dimension order = XYCZT (certain)
	Pixel type = float
	Valid bits per pixel = 32
	Metadata complete = false
	Thumbnail series = false
	-----
	Plane #0 <=> Z 0, C 0, T 0


Reading pixel data (0-0)
	Read 1/1 planes (100%)
[done]
```

All is good.

My suspicion is the reader is failing here:

   https://github.com/openmicroscopy/bioformats/blob/master/components/formats-gpl/src/loci/formats/in/KodakReader.java#L236

As it cannot decode what would appear to be a Hexdecimal? (0xED) value. In this case 237, which seems too high of a CCD temp to me but it's what's in the file.

**Comment by melissalinkert** [comment]
Thank you for reporting this, @andrewjanke.  A pull request with a proposed fix is now open (https://github.com/openmicroscopy/bioformats/pull/2492), so we'll review this for the next release of Bio-Formats.
