### ISSUE TITLE
Bio-Formats Exporter throws NullPointerException

### ISSUE THREAD

**Issue by imagejan** [openmicroscopy/bioformats#2752]
To reproduce, run the following macro in Fiji:

```
run("Mitosis (26MB, 5D stack)");
run("Bio-Formats Exporter", "save=[C:\\temp\\test.ics]");
```

the exception thrown is:

```
(Fiji Is Just) ImageJ 2.0.0-rc-56/1.51h; Java 1.8.0_112 [64-bit]; Windows 7 6.1; 331MB of 96000MB (<1%)
 
java.lang.NullPointerException
	at loci.plugins.out.Exporter.run(Exporter.java:443)
	at loci.plugins.LociExporter.run(LociExporter.java:75)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:265)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:219)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:63)
	at ij.IJ.run(IJ.java:297)
	at ij.macro.Functions.doRun(Functions.java:601)
	at ij.macro.Functions.doFunction(Functions.java:96)
	at ij.macro.Interpreter.doStatement(Interpreter.java:230)
	at ij.macro.Interpreter.doStatements(Interpreter.java:218)
	at ij.macro.Interpreter.run(Interpreter.java:115)
	at ij.macro.Interpreter.run(Interpreter.java:85)
	at ij.macro.Interpreter.run(Interpreter.java:96)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:155)
	at ij.IJ.runMacro(IJ.java:134)
	at ij.IJ.runMacro(IJ.java:123)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1039)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1035)
	at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:986)
	at net.imagej.legacy.IJ1Helper.runMacro(IJ1Helper.java:1035)
	at net.imagej.legacy.plugin.IJ1MacroEngine.eval(IJ1MacroEngine.java:97)
	at net.imagej.legacy.plugin.IJ1MacroEngine.eval(IJ1MacroEngine.java:144)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:177)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by melissalinkert** [comment]
Thanks for reporting this, @imagejan.  I can reproduce the error message; a proposed fix is here: https://github.com/openmicroscopy/bioformats/pull/2754

**Comment by sbesson** [comment]
Closing as per #2754.
