### ISSUE TITLE
Allow `uint16` TIFF to JPG conversion in bfconvert 

### ISSUE THREAD

**Issue by burgerga** [openmicroscopy/bioformats#3149]
I am working with a lot of `uint16` TIFF images, and they show up black in almost all image viewers. So for visual inspection and for making movies I usually convert them to JPEG and go from there. However this is quite difficult using existing tools, so I'm hoping that bioformats can help with this :)

I have attached [demo_uint16.tiff.zip](https://github.com/openmicroscopy/bioformats/files/2002924/demo_uint16.tiff.zip) (created with bfconvert from a Nikon ND2).

What happens when I try to convert it?

* bftools:

  ```bash
  $ bfconvert -version
  Version: 5.8.2
  Build date: 20 April 2018
  VCS revision: 07ecd9a5d239985f8ae57462c12124c2fa5ccd9b
  
  $ bfconvert demo_uint16.tiff out.jpg
  demo_uint16.tiff
  TiffDelegateReader initializing demo_uint16.tiff
  Reading IFDs
  Populating metadata
  Checking comment style
  Populating OME metadata
  [Tagged Image File Format] -> out.jpg [JPEG]
  Exception in thread "main" loci.formats.FormatException: Unsupported image type 'uint16'.
          at loci.formats.FormatWriter.checkParams(FormatWriter.java:424)
          at loci.formats.out.ImageIOWriter.saveBytes(ImageIOWriter.java:87)
          at loci.formats.FormatWriter.saveBytes(FormatWriter.java:123)
          at loci.formats.ImageWriter.saveBytes(ImageWriter.java:246)
          at loci.formats.tools.ImageConverter.convertPlane(ImageConverter.java:644)
          at loci.formats.tools.ImageConverter.testConvert(ImageConverter.java:563)
          at loci.formats.tools.ImageConverter.main(ImageConverter.java:884)
  ```
* ImageMagick

  ```
  $ convert -version
  Version: ImageMagick 7.0.7-26 Q16 x86_64 2018-03-12 http://www.imagemagick.org
  Copyright: © 1999-2018 ImageMagick Studio LLC
  License: http://www.imagemagick.org/script/license.php
  Features: Cipher DPC HDRI Modules OpenCL OpenMP 
  Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
  
  $ convert demo_uint16.tiff out.jpg
  convert: Can not read TIFF directory count. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/650.
  convert: Failed to read directory at offset 2117432. `TIFFReadDirectory' @ error/tiff.c/TIFFErrors/650.

What I do now using `python-bioformats` (far from ideal):

```python
#!/usr/bin/env python3
import argparse
parser = argparse.ArgumentParser(description="Convert 16-bit TIFF to JPEG")
parser.add_argument("ifile", help="input file")
parser.add_argument("ofile", help="output file")
args = parser.parse_args()

import javabridge
import bioformats
import scipy
from scipy.misc import imsave

javabridge.start_vm(class_path=bioformats.JARS)

img = bioformats.load_image(args.ifile, rescale=False)
scipy.misc.imsave(args.ofile, img, "JPEG")

javabridge.kill_vm()
```
The rescaling happens in `scipy.misc.imsave` I believe, so I turned it of for `bioformats.load_image`. Surely there should be an easier way? ;)

**EDIT:**

```python
#!/usr/bin/env python3

import tifffile as tiff
import scipy
from scipy.misc import imsave

im = tiff.imread('demo_uint16.tiff')
scipy.misc.imsave('out.jpg', im, "JPEG")
```
works as well, despite some warnings about a corrupted file:
```
/home/gerhard/anaconda3/lib/python3.6/site-packages/tifffile/tifffile.py:2034: UserWarning: invalid ImageJ metadata or corrupted file
  warnings.warn('invalid ImageJ metadata or corrupted file')
/home/gerhard/anaconda3/lib/python3.6/site-packages/tifffile/tifffile.py:2894: UserWarning: invalid page offset (2117432)
  warnings.warn('invalid page offset (%i)' % offset)
```
Since this looks like the error that ImageMagick gives, is my TIFF alright?

**Comment by burgerga** [comment]
Thanks for your reply, it seems that this bug is indeed the cause of my headaches. After
rerunning `bfconvert` to fix the TIFF I can use ImageMagick again to get a JPEG/PNG.
