### ISSUE TITLE
Issue with using Bio-Formats from Python Script in headless mode

### ISSUE THREAD

**Issue by sebi06** [openmicroscopy/bioformats#3357]
HI guys,

I already asked around at the image.sc forum. See this post here for details: https://forum.image.sc/t/strange-issue-with-using-bioformats-from-python-script-in-headless-mode-only/24937/3?u=sebi06

But so far nobody seems to have an idea what is going on. In short:

- I have a python script in Fiji that saves an image as OME-TIFF using Bio-Formats, **which works fine when used from Fiji directly**
- When I use the same code from headless mode I get an NullPointerException
- the "critical line of code is this one:

```
IJ.run(imps[ch], "Bio-Formats Exporter", "save=[" + savepath + "] compression=Uncompressed")
```

I am not sure if this is a bioformats issues directly, but any help or hint is really appreciated.

Sebi

```
C:\Users\m1srh\Documents\Fiji
λ ImageJ-win64.exe --ij2 --headless --console --run "C:\Users\m1srh\Documents\Fiji\scripts\channelsplit.py" "FILENAME='C:\\Temp\\input\\3CH_Z-Stack_RN.czi'"

C:\Users\m1srh\Documents\Fiji
λ Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/m1srh/DOCUME~1/Fiji/jars/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/m1srh/DOCUME~1/Fiji/jars/slf4j-simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
11:35:22,957 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-test.xml] at [jar:file:/C:/Users/m1srh/DOCUME~1/Fiji/jars/mitobo-1.8.4.jar!/logback-test.xml]
11:35:22,958 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs multiple times on the classpath.
11:35:22,958 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs at [jar:file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/Mosaic_ToolSuite/MosaicSuite-1.0.18_Full.jar!/logback-test.xml]
11:35:22,958 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs at [jar:file:/C:/Users/m1srh/DOCUME~1/Fiji/jars/mitobo-1.8.4.jar!/logback-test.xml]
11:35:22,978 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@21f8e55f - URL [jar:file:/C:/Users/m1srh/DOCUME~1/Fiji/jars/mitobo-1.8.4.jar!/logback-test.xml] is not of type file
11:35:23,080 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:35:23,083 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:35:23,091 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
11:35:23,097 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:35:23,159 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
11:35:23,159 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
11:35:23,160 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:35:23,161 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@d5ce97f - Registering current configuration as safe fallback point

SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[INFO] Overriding BIOP Run Macro...; identifier: command:ch.epfl.biop.macrorunner.B_Run_Macro; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/BIOP/B_Run_Macro-1.0.0-SNAPSHOT.jar
[INFO] Overriding Get Spine From Circle Rois; identifier: command:Cirlces_Based_Spine; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/Max_Inscribed_Circles-1.1.0.jar
[INFO] Overriding Adaptive Threshold; identifier: command:com.mycompany.adaptivethresholdj.Adaptive_ThresholdJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/AdaptiveThresholdJ-1.0-SNAPSHOT.jar
[INFO] Overriding BGR Histogram Comparison; identifier: command:com.mycompany.bgrhistogramcomparisonj.BGR_Histogram_ComparisonJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/BGRHistogramComparisonJ-1.0-SNAPSHOT.jar
[INFO] Overriding BlackHat; identifier: command:com.mycompany.blackhatj.BlackHatJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/BlackHatJ-1.0-SNAPSHOT.jar
[INFO] Overriding Canny Edge Detection; identifier: command:com.mycompany.cannyedgedetectionj.CannyEdgeDetectionJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/CannyEdgeDetectionJ-1.0-SNAPSHOT.jar
[INFO] Overriding Convex Hull from Polygon ROI; identifier: command:com.mycompany.convexhullfrompolygonroij.ConvexHullFromPolygonROIJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/ConvexHullFromPolygonROIJ-1.0-SNAPSHOT.jar
[INFO] Overriding Detect circles; identifier: command:com.mycompany.detectcircles.DetectCirclesJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/DetectCirclesJ-1.0-SNAPSHOT.jar
[INFO] Overriding Face detection; identifier: command:com.mycompany.facedetectionj.FaceDetectionJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/FaceDetectionJ-1.0-SNAPSHOT.jar
[INFO] Overriding Find contours; identifier: command:com.mycompany.findcontoursj.FindContoursJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/FindContoursJ-1.0-SNAPSHOT.jar
[INFO] Overriding HSV Histogram Comparison; identifier: command:com.mycompany.hsvhistogramcomparisonj.HSV_Histogram_ComparisonJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/HSVHistogramComparisonJ-1.0-SNAPSHOT.jar
[INFO] Overriding High dynamic range imaging; identifier: command:com.mycompany.highdynamicrangeimagingj.High_Dynamic_Range_ImagingJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/HighDynamicRangeImagingJ-1.0-SNAPSHOT.jar
[INFO] Overriding Hough lines; identifier: command:com.mycompany.houghlinesj.HoughLinesJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/HoughLinesJ-1.0-SNAPSHOT.jar
[INFO] Overriding Keypoint detector; identifier: command:com.mycompany.keypointdetectorj.KeyPointDetectorJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/KeyPointDetectorJ-1.0-SNAPSHOT.jar
[INFO] Overriding Kmeans clustering; identifier: command:com.mycompany.kmeansclusteringj.KMeans_ClusteringJ; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/KMeansClusteringJ-1.0-SNAPSHOT.jar
[INFO] Overriding Non local means denoising; identifier: command:com.mycompany.nonlocalmeansdenoisingj.Non_Local_Means_DenoisingJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/NonLocalMeansDenoisingJ-1.0-SNAPSHOT.jar

[INFO] Overriding Stitching; identifier: command:com.mycompany.stitchingj.StitchingJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/StitchingJ-1.0-SNAPSHOT.jar
[INFO] Overriding Template matching; identifier: command:com.mycompany.templatematchingj.TemplateMatchingJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/TemplateMatchingJ-1.0-SNAPSHOT.jar
[INFO] Overriding Whitehat; identifier: command:com.mycompany.whitehatj.WhiteHatJ_; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/plugins/IJ-OpenCV-plugins/WhiteHatJ-1.0-SNAPSHOT.jar
[INFO] Overriding Phasor To Image; identifier: script:Time+Gated+Phasor+1.45/Phasor_To_Image.java; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/jars/scijava-common-2.77.0.jar
[INFO] Overriding Timegatedphasor ; identifier: script:Time+Gated+Phasor+1.45/Timegatedphasor_.java; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/jars/scijava-common-2.77.0.jar
[INFO] Overriding Save Image As Tiff Without Prompt; identifier: script:ZenIntegration/Save_Image_As_Tiff_Without_Prompt.java; jar: file:/C:/Users/m1srh/DOCUME~1/Fiji/jars/scijava-common-2.77.0.jar
[INFO] Fiji Script Directory: C:\Users\m1srh\Documents\Fiji\Scripts
[INFO] Opening Image: C:\Temp\input\3CH_Z-Stack_RN.czi
[INFO] Number of Channels to split: 3
java.lang.NullPointerException
        at loci.plugins.out.Exporter.run(Exporter.java:332)
        at loci.plugins.LociExporter.run(LociExporter.java:75)
        at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:266)
        at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
        at ij.IJ.runUserPlugIn(IJ.java:231)
        at ij.IJ.runPlugIn(IJ.java:193)
        at ij.Executer.runCommand(Executer.java:137)
        at ij.Executer.run(Executer.java:66)
        at ij.IJ.run(IJ.java:309)
        at ij.IJ.run(IJ.java:373)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206)
        at org.python.core.PyObject.__call__(PyObject.java:515)
        at org.python.core.PyObject.__call__(PyObject.java:519)
        at org.python.pycode._pyx0.f$0(C:/Users/m1srh/Documents/Fiji/scripts/channelsplit.py:61)
        at org.python.pycode._pyx0.call_function(C:/Users/m1srh/Documents/Fiji/scripts/channelsplit.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1614)
        at org.python.core.__builtin__.eval(__builtin__.java:497)
        at org.python.core.__builtin__.eval(__builtin__.java:501)
        at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
        at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
        at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by sbesson** [comment]
I assume this is fixed by the solution proposed in https://forum.image.sc/t/strange-issue-with-using-bioformats-from-python-script-in-headless-mode-only/24937/4 i.e. enabling `windowless` mode. Closing. Let us know if this issue persists for another reason.

**Comment by sebi06** [comment]
Obviously you are correct. The issues is fixed by: https://forum.image.sc/t/strange-issue-with-using-bioformats-from-python-script-in-headless-mode-only/24937/4.
